# Generated by Django 2.2.1 on 2019-06-08 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 6, 13, 47, 881008, tzinfo=utc)),
        ),
    ]
