# Generated by Django 2.2.1 on 2019-06-08 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190608_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 6, 15, 2, 145275, tzinfo=utc)),
        ),
    ]
