# Generated by Django 2.2.2 on 2019-06-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='marks',
            new_name='sal',
        ),
    ]
