# Generated by Django 2.2.2 on 2019-06-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190607_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='student1',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo')),
                ('rollno', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            bases=('testapp.contactinfo',),
        ),
        migrations.CreateModel(
            name='teacher1',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo')),
                ('subject', models.CharField(max_length=100)),
                ('sal', models.FloatField()),
            ],
            bases=('testapp.contactinfo',),
        ),
    ]
