# Generated by Django 2.2.1 on 2019-05-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sal', models.FloatField()),
                ('ph_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
