# Generated by Django 2.2.1 on 2019-05-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sal', models.FloatField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
